### ISSUE TITLE
Tag 2 Folie 60 verbessern

### ISSUE THREAD

**Issue by FabianGrote** [FIUS/theo-vorkurs-folien#13]
Warum reichen die beiden Fälle?
Einfacheres Beisiel zur Fallunterscheidung oder einfacher machen (z.B. Stück für Stück mit "Animationen").

**Comment by welkerje** [comment]
Ich glaube es sollte von den Präsentierenden leicht zu erklären sein, dass die Fälle _n ist gerade_ und _n ist ungerade_ mit n aus Nat alle Möglichkeiten abdeckt
