### ISSUE TITLE
Foliensatz 1 - Kontraposition

### ISSUE THREAD

**Issue by welkerje** [FIUS/theo-vorkurs-folien#35]
In einem Beispiel zu logischen Operationen steht  "wie gezeigt wurde" aber es wurde nichts gezeigt. Wurde etwas umsortiert?

**Comment by ModellbahnFreak** [comment]
Nicht dass ich sehe, 

Die frage ist ob man ne Folie macht auf der man Kontraposition erklärt oder ob man das nur als Notiz macht
