### ISSUE TITLE
Metropolis Blöcke tun komische Sachen wenn deren Hintergrund transparent ist

### ISSUE THREAD

**Issue by welkerje** [FIUS/theo-vorkurs-folien#42]
Die Überschrift rückt dem Inhalt von Blöcken etwas hart auf die Pelle. Lässt sich da LaTeX Magie tun?

**Comment by ModellbahnFreak** [comment]
Dank @marzipankaiser gelöst:

In preamble folgenden Code hinzugefügt: 
```latex
\addtobeamertemplate{block begin}{}{\vskip 0em}
\addtobeamertemplate{block alerted begin}{}{\vskip 0em}
\addtobeamertemplate{block example begin}{}{\vskip 0em}
```

Warum auch imer ein skip von 0 die Blöcke dazu zwingt normal auszusehen 😕
