### ISSUE TITLE
Tag 3 Reihenfolge Ableiten Produktionen

### ISSUE THREAD

**Issue by nk-coding** [FIUS/theo-vorkurs-folien#6]
* möglicherweise Ableiten vor Aufgaben / Beispielen zu Produktionen, da Wissen notwendig (für erklären)
    * Problem: Dann 2 Aufgabenblöcke mit ähnlichen Aufgaben hintereinander
    * Problem: Dann ist Labyrinth Ende, kein satisfying Ende

**Comment by ModellbahnFreak** [comment]
Wird nicht als Problem gesehen. Es zu ändern würde bedingen den Aufgabenblock zu ändern
