### ISSUE TITLE
Tag 5: Beweis und Aufgaben

### ISSUE THREAD

**Issue by nk-coding** [FIUS/theo-vorkurs-folien#7]
* Beweis Typ 3 = DEA soll in Folien bleiben, wird von einzelnen Hörsälen möglicherweise geskipped
* Aufgaben erstellen [Details hinzufügen]
* Vorteil Beweis
    * sehen echten Beweis, nicht nur Einzeiler
    * gut für obere 10%
* Nachteil Beweis
    * schlechter Abschluss, kein satisfying Ende
    * viele steigen möglicherweise aus

**Comment by ModellbahnFreak** [comment]
Beweis ist im Anhang; Sollte da auch bleiben, da er in den Folien referenziert wird

Punkt 2 (Aufgaben erstellen) nicht nachvollziehbar
