### ISSUE TITLE
Tag 3 Bugs

### ISSUE THREAD

**Issue by nk-coding** [FIUS/theo-vorkurs-folien#9]
* In der finde Produktionsregeln Aufgabe Reihenfolge ist "des Todes" unlogisch
    * bewusst nicht nur nach Aufgabenschwere, damit sie lernen dass Aufgaben auch übersprungen werden können
* Telefon Aufgabe verwirrt jeden / nicht allzu relevant
    * vllt stattdessen was passiert bei Induktion wenn man falsche Aussage zeigen will
    * Bsp. 2^n <= n!
* IV verbessern?
    * Nicht nur ein Standartsatz, sondern Aussage nochmal hinschreiben dass klar ist was man verwenden darf

**Comment by ModellbahnFreak** [comment]
- Reihenfolge Aufgabe: Wird so gelassen, sonst ähnliche Aufgaben zu nah
- Telefonaufgabe: Lassen, wichtig ist gut zu erklären
- IV verbessern: Tim findet es nicht wichtig
